# Generated by Django 5.2.7 on 2025-10-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instituicao_ensino',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instituição de Ensino'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('ORGANIZADOR', 'Organizador')], default='ALUNO', max_length=15, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
