# Generated by Django 5.2.7 on 2025-10-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='apresentador',
            field=models.CharField(default='A Definir', max_length=255),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome_evento',
            field=models.CharField(default='Nome do Evento', max_length=255),
        ),
    ]
