# Generated by Django 5.2.7 on 2025-10-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_evento_apresentador_evento_nome_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='horario',
            new_name='horario_fim',
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_inicio',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
