# Generated by Django 5.2.7 on 2025-10-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_horario_evento_horario_fim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data_final',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_inicial',
        ),
    ]
