# Generated by Django 5.2.6 on 2025-10-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_data_final_evento_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='apresentador',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome_evento',
            field=models.CharField(max_length=255),
        ),
    ]
